# Generated by Django 3.1.5 on 2022-08-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djaml', '0010_auto_20220825_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='employee_residence',
        ),
    ]
